# Generated by Django 6.0.5 on 2026-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('categoryid', models.AutoField(db_column='categoryid', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='categoryname', max_length=150, unique=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'tbl_product_category_master',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionid', models.AutoField(db_column='regionid', primary_key=True, serialize=False)),
                ('regionname', models.CharField(db_column='regionname', max_length=150, unique=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'db_table': 'tbl_region_master',
            },
        ),
    ]
