# Generated by Django 6.0.5 on 2026-06-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('leadsourceid', models.AutoField(db_column='leadsourceid', primary_key=True, serialize=False)),
                ('leadsourcename', models.CharField(db_column='leadsourcename', max_length=150, unique=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_lead_source_master',
            },
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('statusid', models.AutoField(db_column='statusid', primary_key=True, serialize=False)),
                ('statusname', models.CharField(db_column='statusname', max_length=150, unique=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_lead_status_master',
            },
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='added_dts',
            field=models.CharField(blank=True, db_column='added_dts', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='added_dts',
            field=models.CharField(blank=True, db_column='added_dts', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('leadid', models.AutoField(db_column='leadid', primary_key=True, serialize=False)),
                ('personname', models.CharField(db_column='personname', max_length=150)),
                ('gender', models.CharField(blank=True, db_column='gender', max_length=50, null=True)),
                ('companyname', models.CharField(blank=True, db_column='companyname', max_length=200, null=True)),
                ('contactno', models.CharField(blank=True, db_column='contactno', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=150, null=True)),
                ('city', models.CharField(blank=True, db_column='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, db_column='state', max_length=100, null=True)),
                ('businessneed', models.TextField(blank=True, db_column='businessneed', null=True)),
                ('lead_gen_date', models.DateField(blank=True, db_column='lead_gen_date', null=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
                ('executiveid', models.IntegerField(db_column='executiveid')),
                ('regionid', models.ForeignKey(db_column='regionid', on_delete=django.db.models.deletion.CASCADE, to='leads.region')),
                ('leadsourceid', models.ForeignKey(db_column='leadsourceid', on_delete=django.db.models.deletion.CASCADE, to='leads.leadsource')),
                ('statusid', models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.CASCADE, to='leads.leadstatus')),
            ],
            options={
                'db_table': 'tbl_lead_pipeline',
            },
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('followupid', models.AutoField(db_column='followupid', primary_key=True, serialize=False)),
                ('executiveid', models.IntegerField(db_column='executiveid')),
                ('actiontaken', models.CharField(db_column='actiontaken', max_length=255)),
                ('remarks', models.TextField(blank=True, db_column='remarks', null=True)),
                ('followupdate', models.DateField(blank=True, db_column='followupdate', null=True)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
                ('executive_name', models.CharField(blank=True, db_column='executive_name', max_length=150, null=True)),
                ('leadid', models.ForeignKey(db_column='leadid', on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('leadstatusid', models.ForeignKey(db_column='leadstatusid', on_delete=django.db.models.deletion.CASCADE, to='leads.leadstatus')),
            ],
            options={
                'db_table': 'tbl_lead_followup_history',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.AutoField(db_column='productid', primary_key=True, serialize=False)),
                ('productname', models.CharField(db_column='productname', max_length=150)),
                ('is_active', models.IntegerField(db_column='is_active', default=1)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
                ('categoryid', models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.CASCADE, to='leads.productcategory')),
            ],
            options={
                'db_table': 'tbl_product_master',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='leads.product'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('territoryid', models.AutoField(db_column='territoryid', primary_key=True, serialize=False)),
                ('territoryname', models.CharField(db_column='territoryname', max_length=150)),
                ('added_by', models.CharField(blank=True, db_column='added_by', max_length=100, null=True)),
                ('added_dts', models.CharField(blank=True, db_column='added_dts', max_length=100, null=True)),
                ('regionid', models.ForeignKey(db_column='regionid', on_delete=django.db.models.deletion.CASCADE, to='leads.region')),
            ],
            options={
                'db_table': 'tbl_territory_master',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='territoryid',
            field=models.ForeignKey(db_column='territoryid', on_delete=django.db.models.deletion.CASCADE, to='leads.territory'),
        ),
    ]
