# Generated by Django 6.0.5 on 2026-06-17 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadsource_leadstatus_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='leadsourceid',
            field=models.ForeignKey(db_column='leadsourceid', on_delete=django.db.models.deletion.PROTECT, to='leads.leadsource'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.PROTECT, to='leads.product'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='regionid',
            field=models.ForeignKey(db_column='regionid', on_delete=django.db.models.deletion.PROTECT, to='leads.region'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='statusid',
            field=models.ForeignKey(db_column='statusid', on_delete=django.db.models.deletion.PROTECT, to='leads.leadstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='territoryid',
            field=models.ForeignKey(db_column='territoryid', on_delete=django.db.models.deletion.PROTECT, to='leads.territory'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='leadid',
            field=models.ForeignKey(db_column='leadid', on_delete=django.db.models.deletion.PROTECT, to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='leadstatusid',
            field=models.ForeignKey(db_column='leadstatusid', on_delete=django.db.models.deletion.PROTECT, to='leads.leadstatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoryid',
            field=models.ForeignKey(db_column='categoryid', on_delete=django.db.models.deletion.PROTECT, to='leads.productcategory'),
        ),
        migrations.AlterField(
            model_name='territory',
            name='regionid',
            field=models.ForeignKey(db_column='regionid', on_delete=django.db.models.deletion.PROTECT, to='leads.region'),
        ),
    ]
