# Generated by Django 6.0.5 on 2026-06-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Source',
            fields=[
                ('LeadSourceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('LeadSourceName', models.CharField(max_length=150)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lead_Source',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=150)),
                ('CategoryID', models.IntegerField(blank=True, null=True)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=150)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('LeadID', models.BigAutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=150)),
                ('Email', models.EmailField(blank=True, max_length=150, null=True)),
                ('ContactNo', models.CharField(blank=True, max_length=20, null=True)),
                ('CompanyName', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.CharField(blank=True, max_length=100, null=True)),
                ('TerritoryID', models.IntegerField(blank=True, null=True)),
                ('StatusID', models.IntegerField()),
                ('BusinessNeed', models.TextField(blank=True, null=True)),
                ('Lead_Gen_Date', models.DateTimeField(blank=True, null=True)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
                ('ExecutiveID', models.IntegerField(blank=True, null=True)),
                ('source', models.ForeignKey(db_column='LeadSourceID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeadsData.lead_source')),
                ('product', models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeadsData.product')),
                ('region', models.ForeignKey(db_column='RegionID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='LeadsData.region')),
            ],
            options={
                'db_table': 'Lead',
            },
        ),
    ]
