# Generated by Django 6.0.5 on 2026-06-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadsData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_Status',
            fields=[
                ('StatusID', models.BigAutoField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=150)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Lead_Status',
            },
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('CategoryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=150)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Product_Category',
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='StatusID',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='TerritoryID',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='region',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='product',
            name='CategoryID',
        ),
        migrations.AddField(
            model_name='lead',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='BusinessNeed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='CompanyName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ContactNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ExecutiveID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Lead_Gen_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='State',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Added_By',
            field=models.CharField(default='system', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
        migrations.AlterModelTable(
            name='region',
            table='Region',
        ),
        migrations.CreateModel(
            name='Lead_Follow_Up',
            fields=[
                ('FollowUpID', models.BigAutoField(primary_key=True, serialize=False)),
                ('ExecutiveID', models.IntegerField()),
                ('ActionTaken', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
                ('FollowUpDate', models.DateTimeField()),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
                ('Executive_Name', models.CharField(max_length=150)),
                ('Lead', models.ForeignKey(db_column='LeadID', on_delete=django.db.models.deletion.CASCADE, to='LeadsData.lead')),
                ('LeadStatus', models.ForeignKey(db_column='LeadStatusID', on_delete=django.db.models.deletion.PROTECT, to='LeadsData.lead_status')),
            ],
            options={
                'db_table': 'Lead_Follow_Up',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='Status',
            field=models.ForeignKey(db_column='StatusID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.lead_status'),
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(db_column='CategoryID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.product_category'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('TerritoryID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TerritoryName', models.CharField(max_length=150)),
                ('Added_By', models.CharField(default='system', max_length=100)),
                ('Added_Dts', models.DateTimeField(auto_now_add=True)),
                ('Region', models.ForeignKey(db_column='RegionID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.region')),
            ],
            options={
                'db_table': 'Territory',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='Territory',
            field=models.ForeignKey(db_column='TerritoryID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.territory'),
        ),
        migrations.AddField(
            model_name='lead',
            name='Product',
            field=models.ForeignKey(db_column='ProductID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.product'),
        ),
        migrations.AddField(
            model_name='lead',
            name='Region',
            field=models.ForeignKey(db_column='RegionID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.region'),
        ),
        migrations.AddField(
            model_name='lead',
            name='Source',
            field=models.ForeignKey(db_column='LeadSourceID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.lead_source'),
        ),
    ]
