# Generated by Django 6.0.5 on 2026-06-09 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadsData', '0002_lead_status_product_category_remove_lead_statusid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='BusinessNeed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='City',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='CompanyName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ContactNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Email',
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ExecutiveID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Lead_Gen_Date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='State',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead_follow_up',
            name='ActionTaken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead_follow_up',
            name='ExecutiveID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead_follow_up',
            name='Executive_Name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead_follow_up',
            name='LeadStatus',
            field=models.ForeignKey(db_column='LeadStatusID', null=True, on_delete=django.db.models.deletion.PROTECT, to='LeadsData.lead_status'),
        ),
        migrations.AlterField(
            model_name='lead_follow_up',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
