# Generated by Django 6.0.5 on 2026-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeadsData', '0004_alter_lead_personname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_main_admin',
            field=models.BooleanField(default=False),
        ),
    ]
