# Generated by Django 6.0.5 on 2026-06-24 09:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('LeadSourceID', models.IntegerField(primary_key=True, serialize=False)),
                ('LeadSourceName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('StatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('Is_Active', models.BooleanField(default=True)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=200)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionID', models.AutoField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('LeadID', models.AutoField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('CompanyName', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('BusinessNeed', models.TextField()),
                ('Lead_Gen_Date', models.DateField()),
                ('ExecutiveID', models.IntegerField()),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
                ('LeadSourceID', models.ForeignKey(db_column='LeadSourceID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadsource')),
                ('StatusID', models.ForeignKey(db_column='StatusID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadstatus')),
                ('ProductID', models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.product')),
                ('RegionID', models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('FollowUpID', models.IntegerField(primary_key=True, serialize=False)),
                ('ExecutiveID', models.IntegerField()),
                ('ActionTaken', models.TextField()),
                ('Remarks', models.TextField()),
                ('FollowUpDate', models.DateField()),
                ('Executive_Name', models.CharField(max_length=200)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
                ('LeadID', models.ForeignKey(db_column='LeadID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.lead')),
                ('LeadStatusID', models.ForeignKey(db_column='LeadStatusID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadstatus')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='CategoryID',
            field=models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.productcategory'),
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('TerritoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('TerritoryName', models.CharField(max_length=200)),
                ('Added_By', models.CharField(blank=True, max_length=100)),
                ('Added_Dts', models.DateTimeField(default=django.utils.timezone.now)),
                ('RegionID', models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.region')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='TerritoryID',
            field=models.ForeignKey(db_column='TerritoryID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.territory'),
        ),
    ]
