# Generated by Django 6.0.5 on 2026-06-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('LeadID', models.IntegerField(primary_key=True, serialize=False)),
                ('PersonName', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=20)),
                ('CompanyName', models.CharField(max_length=200)),
                ('ContactNo', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('TerritoryID', models.IntegerField()),
                ('RegionID', models.IntegerField()),
                ('ProductID', models.IntegerField()),
                ('StatusID', models.IntegerField()),
                ('LeadSourceID', models.IntegerField()),
                ('BusinessNeed', models.TextField()),
                ('Lead_Gen_Date', models.DateField()),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
                ('ExecutiveID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadFollowUp',
            fields=[
                ('FollowUpID', models.IntegerField(primary_key=True, serialize=False)),
                ('LeadID', models.IntegerField()),
                ('ExecutiveID', models.IntegerField()),
                ('ActionTaken', models.TextField()),
                ('Remarks', models.TextField()),
                ('LeadStatusID', models.IntegerField()),
                ('FollowUpDate', models.DateField()),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
                ('Executive_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('LeadSourceID', models.IntegerField(primary_key=True, serialize=False)),
                ('LeadSourceName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('StatusID', models.IntegerField(primary_key=True, serialize=False)),
                ('StatusName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=200)),
                ('CategoryID', models.IntegerField()),
                ('Is_Active', models.BooleanField()),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('CategoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=200)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('RegionID', models.IntegerField(primary_key=True, serialize=False)),
                ('RegionName', models.CharField(max_length=100)),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('TerritoryID', models.IntegerField(primary_key=True, serialize=False)),
                ('TerritoryName', models.CharField(max_length=200)),
                ('RegionID', models.IntegerField()),
                ('Added_By', models.CharField(max_length=100)),
                ('Added_Dts', models.DateTimeField()),
            ],
        ),
    ]
