# Generated by Django 6.0.5 on 2026-06-04 11:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lead',
            name='LeadSourceID',
            field=models.ForeignKey(db_column='LeadSourceID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadsource'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='ProductID',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.product'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='RegionID',
            field=models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.region'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='StatusID',
            field=models.ForeignKey(db_column='StatusID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadstatus'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='TerritoryID',
            field=models.ForeignKey(db_column='TerritoryID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.territory'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadID',
            field=models.ForeignKey(db_column='LeadID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.lead'),
        ),
        migrations.AlterField(
            model_name='leadfollowup',
            name='LeadStatusID',
            field=models.ForeignKey(db_column='LeadStatusID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.leadstatus'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadstatus',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='CategoryID',
            field=models.ForeignKey(db_column='CategoryID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='region',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='region',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='territory',
            name='Added_By',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='territory',
            name='Added_Dts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='territory',
            name='RegionID',
            field=models.ForeignKey(db_column='RegionID', on_delete=django.db.models.deletion.CASCADE, to='leadapp.region'),
        ),
    ]
